# Generated by Django 4.1.7 on 2023-03-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
