# Generated by Django 4.1.7 on 2023-03-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="seller_id",
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
    ]
