# Generated by Django 4.1.7 on 2023-03-06 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=127)),
                ("description", models.TextField(null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.CharField(max_length=127)),
                ("stock", models.IntegerField()),
                ("is_available", models.BooleanField(default=True, null=True)),
                (
                    "carts",
                    models.ManyToManyField(related_name="products", to="carts.cart"),
                ),
            ],
        ),
    ]
